<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <PackageId>FFXIVOcelot.Mechanic</PackageId>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ocelot\Ocelot.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="ECommons" Version="3.2.1.20" />
    </ItemGroup>
</Project>
