<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <PackageId>FFXIVOcelot.ECommons</PackageId>
        <IsPackable>false</IsPackable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Ocelot\Ocelot.csproj"/>
        <PackageReference Include="ECommons" Version="3.2.1.21" />
    </ItemGroup>
</Project>
